"""Declarative rule engine shared by policy, classification and scanning (ADR-0012)."""

from ai_arbiter.core.rules.decision import ENGINE_VERSION, Decision, DecisionKind, facts_digest
from ai_arbiter.core.rules.engine import (
    ConditionTrace,
    Evaluation,
    Facts,
    FactValue,
    OpenRule,
    RuleEvaluationError,
    RuleMatch,
    RulePackError,
    condition_state,
    evaluate,
    evaluate_partial,
    load_packaged_pack,
    load_rule_pack,
    packaged_versions,
    parse_rule_pack,
)
from ai_arbiter.core.rules.schema import (
    FactSpec,
    FactType,
    LegalRef,
    LegalSource,
    OutcomeObligation,
    Regulation,
    Rule,
    RuleKind,
    RulePack,
)

__all__ = [
    "ENGINE_VERSION",
    "ConditionTrace",
    "Decision",
    "DecisionKind",
    "Evaluation",
    "FactSpec",
    "FactType",
    "FactValue",
    "Facts",
    "LegalRef",
    "LegalSource",
    "OpenRule",
    "OutcomeObligation",
    "Regulation",
    "Rule",
    "RuleEvaluationError",
    "RuleKind",
    "RuleMatch",
    "RulePack",
    "RulePackError",
    "condition_state",
    "evaluate",
    "evaluate_partial",
    "facts_digest",
    "load_packaged_pack",
    "load_rule_pack",
    "packaged_versions",
    "parse_rule_pack",
]
