"""The compliance commands end to end. Synchronous: the CLI runs its own event loop."""

import re
import sqlite3
from pathlib import Path

from typer.testing import CliRunner

from ai_arbiter.cli.main import app

runner = CliRunner()
EXAMPLES = str(Path(__file__).parents[2] / "examples" / "systems.yaml")


def arbiter(*arguments: str, ok: bool = True) -> str:
    result = runner.invoke(app, list(arguments))
    assert (result.exit_code == 0) is ok, result.output
    return result.output


def workspace() -> None:
    arbiter("init")
    arbiter("systems", "apply", "-f", EXAMPLES)


def finding_id(rule_text: str, system: str) -> str:
    for line in arbiter("findings", "list").splitlines():
        if rule_text in line and system in line:
            return line.split()[0]
    raise AssertionError(f"no finding '{rule_text}' for {system}")


def test_apply_declares_and_classifies_the_example_systems() -> None:
    arbiter("init")

    first = arbiter("systems", "apply", "-f", EXAMPLES)
    again = arbiter("systems", "apply", "-f", EXAMPLES)

    assert re.search(r"cv-screening\s+created\s+high_risk", first)
    assert re.search(r"call-centre-mood-monitor\s+created\s+prohibited", first)
    assert re.search(r"marketing-copy-generator\s+created\s+undetermined", first)
    assert "indicative until a person reviews them" in first
    assert re.search(r"cv-screening\s+unchanged\s+high_risk", again)


def test_list_shows_tier_and_review_state_in_the_chosen_language() -> None:
    workspace()

    english = arbiter("systems", "list")
    italian = arbiter("systems", "list", "--locale", "it")

    assert re.search(
        r"cv-screening\s+High-risk\s+Indicative, awaiting review\s+CV screening", english
    )
    assert re.search(r"cv-screening\s+Alto rischio\s+Indicativa, in attesa di revisione", italian)
    assert "Error: unsupported locale 'fr'" in arbiter(
        "systems", "list", "--locale", "fr", ok=False
    )


def test_show_explains_a_classification_with_provisions_and_dates() -> None:
    workspace()

    text = arbiter("systems", "show", "cv-screening")

    assert "CV screening (cv-screening)" in text
    assert "Tier: High-risk" in text
    assert "Review: Indicative, awaiting review" in text
    assert "High-risk: recruitment or selection of persons (Annex III(4)(a))." in text
    assert "(6(2), Annex III(4)(a)) [2027-12-02, readiness: not applicable yet]" in text
    assert "Keep the logs automatically generated by the system" in text
    assert "comparison with EUR-Lex by the project owner is still pending" in text
    assert "does not provide legal advice" in text
    assert "compliant" not in text.lower()


def test_show_says_which_obligations_are_addressed_to_another_role() -> None:
    workspace()

    text = arbiter("systems", "show", "customer-support-assistant", "--locale", "it")

    assert "Classe: Obblighi di trasparenza" in text
    assert "(50(1)) [2026-08-02] (for: provider)" in text
    assert "Non fornisce consulenza legale." in text


def test_questions_lists_what_is_missing_ready_for_the_declaration() -> None:
    workspace()

    missing = arbiter("systems", "questions", "marketing-copy-generator")
    complete = arbiter("systems", "questions", "cv-screening")

    assert "questions to answer under 'facts' of 'marketing-copy-generator'" in missing
    assert "  prohibited.social_scoring:" in missing
    assert "(Art. 5(1)(c))" in missing
    assert "  annex3.employment:" in missing
    assert "annex3.employment_recruitment" not in missing
    assert "Every question that could change the result is answered." in complete


def test_facts_lists_every_fact_by_stage_with_its_provision() -> None:
    text = arbiter("systems", "facts")

    assert text.index("[scope]") < text.index("[prohibited]") < text.index("[high_risk]")
    assert "  annex3.employment_recruitment (boolean, Annex III(4)(a))" in text
    assert "  controls.human_oversight_assigned (boolean)" in text
    assert "summaries, not the legal text" in text


def test_a_review_is_recorded_under_the_reviewer_and_the_name_stays_out_of_the_audit_log(
    tmp_path: Path,
) -> None:
    workspace()

    confirmed = arbiter(
        "systems", "review", "cv-screening", "--confirm", "--reviewer", "Ada Lovelace"
    )
    overridden = arbiter(
        "systems",
        "review",
        "loan-pre-screening",
        "--override",
        "high_risk",
        "--reason",
        "The provider's assessment does not cover our use.",
        "--reviewer",
        "Ada Lovelace",
    )
    shown = arbiter("systems", "show", "loan-pre-screening")

    assert "cv-screening: high_risk, confirmed by Ada Lovelace" in confirmed
    assert "loan-pre-screening: high_risk, overridden by Ada Lovelace" in overridden
    assert "Tier: High-risk" in shown
    assert "Review: Set by a reviewer" in shown
    assert "engine: Minimal" in shown
    connection = sqlite3.connect(tmp_path / ".arbiter" / "arbiter.db")
    try:
        principals = connection.execute(
            "SELECT count(*) FROM principal WHERE display_name = 'Ada Lovelace'"
        ).fetchone()
        audit = str(connection.execute("SELECT * FROM audit_entry").fetchall())
    finally:
        connection.close()
    assert principals == (1,)
    assert "Ada Lovelace" not in audit
    assert "classification.confirmed" in audit


def test_review_options_are_checked() -> None:
    workspace()

    both = arbiter("systems", "review", "cv-screening", "--reviewer", "A", ok=False)
    no_reason = arbiter(
        "systems", "review", "cv-screening", "--override", "minimal", "--reviewer", "A", ok=False
    )
    undetermined = arbiter(
        "systems", "review", "marketing-copy-generator", "--confirm", "--reviewer", "A", ok=False
    )
    unknown = arbiter("systems", "show", "nope", ok=False)

    assert "Error: use either --confirm or --override TIER" in both
    assert "Error: an override needs a reason" in no_reason
    assert "Error: an undetermined classification cannot be confirmed" in undetermined
    assert "Error: AI system 'nope' not found" in unknown


def test_classify_one_or_all() -> None:
    arbiter("init")
    arbiter("systems", "apply", "-f", EXAMPLES, "--no-classify")

    one = arbiter("classify", "cv-screening")
    everything = arbiter("systems", "classify", "--all")
    neither = arbiter("classify", ok=False)

    assert re.search(r"cv-screening\s+high_risk\s+new", one)
    assert re.search(r"cv-screening\s+high_risk\s+unchanged", everything)
    assert re.search(r"invoice-data-extraction\s+minimal\s+new", everything)
    assert "Error: name a system, or use --all" in neither


def test_scan_then_review_a_finding_through_its_lifecycle() -> None:
    workspace()

    scanned = arbiter("scan")
    listed = arbiter("findings", "list")
    reference = finding_id("no reference to the provider", "loan-pre-screening")
    shown = arbiter("findings", "show", reference)
    confirmed = arbiter("findings", "review", reference, "--to", "confirmed", "--reviewer", "Ada")
    refused = arbiter(
        "findings", "review", reference, "--to", "false_positive", "--reviewer", "Ada", ok=False
    )
    history = arbiter("findings", "show", reference)

    assert "Scanned 7 systems:" in scanned
    assert "proposals until a person reviews them" in scanned
    assert listed.index("Critical") < listed.index("Low")
    assert "rule:      SCAN-DEROGATION-WITHOUT-ASSESSMENT" in shown
    assert "reference: EU-AI-ACT 6(4)" in shown
    assert "system_key: loan-pre-screening" in shown
    assert f"{reference}: confirmed by Ada" in confirmed
    assert "Error: a finding that is confirmed cannot become false_positive" in refused
    assert "open -> confirmed by a reviewer" in history


def test_a_false_positive_with_a_suppression_and_an_accepted_risk() -> None:
    workspace()
    arbiter("scan")
    owner = finding_id("No owner is named", "cv-screening")
    oversight = finding_id("human oversight", "cv-screening")

    rejected = arbiter(
        "findings",
        "review",
        owner,
        "--to",
        "false_positive",
        "--reviewer",
        "Ada",
        "--reason",
        "Ownership is tracked in the CMDB.",
        "--suppress",
        "rule",
    )
    accepted = arbiter(
        "findings",
        "review",
        oversight,
        "--to",
        "accepted",
        "--reviewer",
        "Ada",
        "--reason",
        "Oversight roles are assigned in Q1.",
        "--until",
        "2099-01-01",
    )
    rescanned = arbiter("scan")
    active = arbiter("findings", "list")
    everything = arbiter("findings", "list", "--all")

    assert "false_positive by Ada" in rejected
    assert "accepted by Ada" in accepted
    assert "suppressed: 7" in rescanned
    assert "No owner is named" not in active
    assert "accepted" in everything
    assert "Error: finding 'zzzzzzzz' not found" in arbiter(
        "findings", "show", "zzzzzzzz", ok=False
    )


def test_findings_list_is_empty_before_the_first_scan() -> None:
    arbiter("init")

    assert arbiter("findings", "list").strip() == "No findings."
    assert "No AI system is declared." in arbiter("systems", "list")


def test_digest_to_standard_output_and_to_files(tmp_path: Path) -> None:
    workspace()
    arbiter("scan")

    printed = arbiter("digest", "run", "--locale", "it")
    written = arbiter(
        "digest", "run", "--locale", "all", "--format", "both", "-o", str(tmp_path / "out")
    )
    files = sorted(path.name for path in (tmp_path / "out").iterdir())

    assert printed.startswith("# Digest giornaliero")
    assert "7 sistemi dichiarati" in printed
    assert written.count("Wrote ") == 4
    assert [name.split(".", 1)[1] for name in files] == ["en.html", "en.md", "it.html", "it.md"]
    html = next((tmp_path / "out").glob("*.en.html")).read_text(encoding="utf-8")
    assert "<h1>Daily digest</h1>" in html
    assert "Error: several outputs need a directory" in arbiter(
        "digest", "run", "--locale", "all", ok=False
    )
    assert "Error: unsupported locale 'fr'" in arbiter("digest", "run", "--locale", "fr", ok=False)
    assert "Error: unsupported format 'pdf'" in arbiter(
        "digest", "run", "--format", "pdf", ok=False
    )


def test_the_worker_classifies_declared_systems_and_stops_when_idle() -> None:
    arbiter("init")
    arbiter("systems", "apply", "-f", EXAMPLES, "--no-classify")
    before = arbiter("systems", "list")

    worked = arbiter("worker", "--once")
    after = arbiter("systems", "list")
    idle = arbiter("worker", "--once")

    assert "Not classified" in before
    assert "Delivered 14 events." in worked
    assert re.search(r"cv-screening\s+High-risk", after)
    assert "Delivered 0 events." in idle


def test_retention_purge_reports_what_it_does() -> None:
    workspace()

    preview = arbiter("retention", "purge", "--dry-run")
    done = arbiter("retention", "purge")
    verified = arbiter("audit", "verify")

    assert "Would delete 0 interactions older than 13 months" in preview
    assert "Deleted 0 interactions older than 13 months" in done
    assert "Deleted 0 dispatched events" in done
    assert "no broken link" in verified
